parameters:
    orientdb:
      root:
        username: "root"
        password: "root"
      database:
        dbname:
          username: root
          password: root
          hostname: localhost
          port: 2424
          token: null