services:
    biberltd.phporient:
        class:        BiberLtd\Bundle\Phorient\Services\PhpOrient
        arguments:    ["@service_container", "%orientdb.default.hostname%", "%orientdb.default.port%", "%orientdb.default.token%"]
    biberltd.class_manager_config:
        class:        BiberLtd\Bundle\Phorient\Services\CMConfig
        arguments:    ["%orientdb.default.hostname%", "%orientdb.default.port%", "%orientdb.default.token%", "%orientdb.default.username%", "%orientdb.default.password%"]
    biberltd.class_manager:
        class:        BiberLtd\Bundle\Phorient\Services\ClassManager
        arguments:    ["@service_container", "@biberltd.class_manager_config"]